TBartl/space-station-13-idle

- src/data/botany.js
I had an icepepper set as a coldpepper.
> Icepepperfix

- src/data/botany.js
Tier one: Heal 5, net 0 stat change when selected.
Tier two: Heal 10, Net +5 stat change when selected.
Tier three: Heal 15, Net +5 stat change when selected. +5 Bonus HP.
Tier four: Heal 20, Net +15 stat change when selected. - 5 Bonus HP.
OR
Heal 5, Net +30 stat change when equipped. -10 bonus HP. This one may be too strong.
> Botany Food has values and stat adjustments

- src/data/tinkering.js
Added crafting levels for tinkering gear.
Fixed one item typo.
Equipment will finish first, I don't know if that's a valid design or not.
> Adds Levels To Tinkers

- src/data/cooking.js
- src/data/fabrication.js
- src/data/items/foodCooking.js
- src/data/items/slotHand.js
- src/data/items/slotPocket.js
Fabrication should be completed with approximately half mechs and half guns/ammo.
Resourcewise that's also balanced with what mining will give you, but not what you'll get from other skills. It will probably be one of the slightly longer skills to level because guns stop being a thing midway through.
Costs are _interesting_ because to balance resources I had to do rather long crafting times.
> Fabrication XP and Sell Costs

- src/state/inventory.js
> Fix purchase bug

- src/data/enemies.js
- src/data/items/slotCompanion.js
Adds pet goats, dogs, mice, and bees.
2% drop rate for the first bunch, 25% for the bees.
10 of a single stat for the first, 1 for each stat on the bee.
Bees also have a 60% flee chance at max level, as they are tier 10.
> Adds Non Slime Companions

- src/data/items/foodCooking.js
- src/data/items/foodOther.js
Nerfs Feet, Buffs cooked items
> Fixes some issues from my last pull

- src/data/graytiding.js
- src/data/items/slotChest.js
- src/data/items/slotHand.js
- src/data/tinkering.js
Reworks Tinkering XP rate, level, sell price, junk drops
Basically a full skill rework.
> Reworks Tinkering XP rate, level, sell price, junk

- src/data/enemies/aiCore.js
- src/data/enemies/arrivalLounge.js
- src/data/enemies/bridge.js
- src/data/enemies/dorms4.js
- src/data/enemies/engineering.js
- src/data/enemies/hopLine.js
- src/data/enemies/kitchen.js
- src/data/enemies/maintenance.js
- src/data/enemies/medical.js
- src/data/enemies/science.js
- src/data/enemies/showroom.js
- src/data/enemies/virology.js
- src/data/items/resourceValidhunting.js
- src/data/tinkering.js
Ups enemy protection values in later zones
Adds the 5 items on the item table that were previously unobtainable to enemies.
Adjusts ticket drop rates. There's still a few that need to move but most should be good now.
Adjusts a significant number of enemy drop tables.
Minor tinkering fix.
> Tickets, Misc, and Protection

- src/data/enemies/aiCore.js
- src/data/enemies/bridge.js
- src/data/enemies/dorms4.js
- src/data/enemies/engineering.js
- src/data/enemies/kitchen.js
- src/data/enemies/science.js
- src/data/enemies/showroom.js
Spices up the remaining dull loot tables.
> Finalizes the drop tables

- src/data/items/slotFace.js
> Fixes the clown mask overlay

- src/data/graytiding.js
> Fixes graytiding typo

- src/data/cooking.js
Fixes the ability to make Babel Pasta.
> Fixes final tier of Pasta Cooking

- src/components/Content/ContentCooking.vue
Fixes the name of Korol Konets, the cooking guide.
> Fixes Korol Konets Name

- src/components/Content/ContentGraytiding.vue
Fixes a privilege typo in graytiding.
> Fixes a privilege typo in graytiding.

- src/components/Content/ContentCooking.vue
I legit have no idea why this line is breaking things, but it is
> Fix: Swapping between the Cook's "Cannibalism" dialogue no longer freezes your game

- src/data/fabrication.js
Fixes the CLARKE fabrication cost up from 10-10-10-10 to 25-50-50-5, bringing it back in line with all the other mechs.
> Fixes the CLARKE fabrication cost

- src/data/cooking.js
- src/data/items/resourceChemistry.js
Fix: The Slippery Burger recipe now requires a banana instead of a pepper.
Fix: The Spicy Burger recipe now requires a pepper instead of a banana.
Improvement: Toxic chemicals, such as mercury and acid, now have a description helping indicate why they have a negative sell price.
> Fixes Burger Recipes, Adds a description to chems.

- src/data/items/slotChest.js
Fixes the price on the mime and assault gygax mechs.
> Fixes the price on the mime and assault gygax mech

- src/data/items/slotChest.js
Fixes the price on the seraph mech
> Also fixes the seraph price

- src/data/items/slotCompanion.js
Fixes Slow type slimes to give equal health to other slimes health
> Fixes Slow type slimes to give equal health to other slimes health

- src/data/items/resourceChemistry.js
Accidently hard nerfed tinkering and buffed tiding potions.
Fixes that.
> Fixes the Tinkering Potion

- src/data/graytiding.js
Fixes the volatile Greytiding potion drop count.
> Fixes the volatile Greytiding potion drop count

- src/data/enemies/aiCore.js
- src/data/enemies/arrivalLounge.js
- src/data/enemies/bridge.js
- src/data/enemies/dorms4.js
- src/data/enemies/engineering.js
- src/data/enemies/hopLine.js
- src/data/enemies/kitchen.js
- src/data/enemies/maintenance.js
- src/data/enemies/medical.js
- src/data/enemies/science.js
- src/data/enemies/showroom.js
- src/data/enemies/virology.js
Increases the drop rate on all boss papers by a maximum of one.
0-1 -> 0-2
0-2 -> 0-3
1-2 -> 1-3
1-3 -> 1-4
Thank you for participating in democracy.
> Increases the drop rate on all boss papers by +1

- src/data/xenobiology.js
Sets Rainbow Slime XP from -200 to +-0.
> Rainbow Slime XP change

- src/data/items/slotLimb.js
Changes adv. magboots and regular around, because...
advanced
> Magboot swap

- src/data/enemies/bridge.js
- src/data/enemies/hopLine.js
- src/data/enemies/medical.js
- src/data/items/slotHand.js
- src/data/tinkering.js
- src/data/zones.js
Adds two new enemies:
Runtime to medbay
Renault to the bridge
Adds two new companions and restats one.
Pet Cat to Runtime
Pet Fox to Renault
Changes the stats on the Pet Corgi.
Thank you Remona for these changes.
Fixes a typo and XP on the level 43 item in tinkering.
> Tinkering Fixes+Renault Runtime Statting

- src/components/Sidebar/Sidebar.vue
for that a e s t h e t i c
remona's suggestion is cool but simplistic and probably won't actually get your attention considering how tiny the health bar is, whereas this is cool and complex 😎 and just generally feels nicer than abrupt changes
> Introduces dynamic colour shifting on healthbar

- src/data/enemies.js
> dynamic tickets

- src/data/enemies/boss60-wizard.js
- src/data/items/resourceValidhunting.js
- src/data/shop.js
> Triple Typo Fix

- src/data/enemies/kitchen.js
Fixes the Skrell Bartender name
> Fixes the Skrell Bartender name

- src/components/Content/ContentSettings.vue
Dead simple; just add chrono time when importing a save file from the past.
> Calculate chrono time on import

- src/components/ItemPopover.vue
https://github.com/TBartl/space-station-13-idle/issues/283
> Add equipment-slot to equipable items popover

- package.json
- src/data/enemies/boss50-cult.js
- src/data/items/resourceChemistry.js
Enemy Nerf: The wraith now takes 30% more damage from all attacks.
Fix: Fixes the icon on the new pill.
> Nerfs the wraith, fixes a pill icon

- src/components/Content/ContentCargonia.vue
- src/components/Content/ContentCult.vue
- src/components/Content/ContentLing.vue
- src/data/cargonia.js
- src/data/cult.js
- src/data/items/slotCompanion.js
- src/data/items/slotHand.js
- src/data/ling.js
Seperates antag jobs into catagories
Cargonia buy and sell costs
This took me too long and for future reference I should just copy the bottom half of a job like chemistry
> Seperates antag jobs into catagories, Cargonia buy and sell costs

- src/components/Content/ContentCargonia.vue
- src/components/Content/ContentLing.vue
- src/components/Content/ContentTraitor.vue
- src/data/cargonia.js
- src/data/enemies/boss10-rev.js
- src/data/enemies/boss20-security.js
- src/data/enemies/boss30-lavaland.js
- src/data/enemies/boss40-nuke.js
- src/data/enemies/boss50-cult.js
- src/data/enemies/boss55-ert.js
- src/data/enemies/boss60-wizard.js
- src/data/items/slotHand.js
- src/data/items/slotNeck.js
Gives boss 3 some luck.
Reduces the health on boss 4 but gives them .2 regen per level category.
Changes the evasion on neck items to luck.
> Restats bosses and neck slot items

- src/components/Content/ContentSettings.vue
- src/main.js
- src/state/settings.js
~~Entirely untested and~~ (mostly) made with web editor
> Adds a setting to show full values of item counts (instead of >9k)

- src/components/Content/ContentCargonia.vue
- src/components/Content/ContentLing.vue
- src/components/Content/ContentTraitor.vue
- src/data/bartending.js
- src/data/chemistry.js
- src/data/enemies/arrivalLounge.js
- src/data/enemies/medical.js
- src/data/enemies/science.js
- src/data/enemies/zombies.js
- src/data/items/foodBartending.js
- src/data/items/resourceChemistry.js
Fixes everything that was reviewed.
Notes to self.
Picture then bold word in descriptions.
oxyen
check f12 for bugs
> 1.3 fixes as requested. Bartending price and quantity corrections.

- src/data/items/slotChest.js
- src/data/items/slotFace.js
- src/data/items/slotJumpsuit.js
- src/data/items/slotLimb.js
Buffs clown items and paramedic jumpsuit
> Buffs clown items and paramedic jumpsuit

- src/data/enemies/boss10-rev.js
- src/data/enemies/boss20-security.js
- src/data/enemies/boss30-lavaland.js
- src/data/enemies/boss40-nuke.js
- src/data/enemies/boss50-cult.js
- src/data/enemies/boss55-ert.js
- src/data/enemies/boss60-wizard.js
Removes the regen from bosses tempfix.
They keep standing up after dying.
> Removes the regen from bosses tempfix

- src/data/enemies/boss10-rev.js
- src/data/enemies/boss20-security.js
- src/data/enemies/boss30-lavaland.js
- src/data/enemies/boss40-nuke.js
- src/data/enemies/boss50-cult.js
- src/data/enemies/boss55-ert.js
- src/data/enemies/boss60-wizard.js
Reverts TBartl/space-station-13-idle#333
> Revert "Removes the regen from bosses tempfix"

- src/data/items/resourceTraitor.js
- src/data/shop.js
Fixes the traitor specific DEsword attack speed
Fixes the Cooking Cloak being unpurchasable.
> Fixes the traitor specific DEsword, Cooking Cloak

- src/data/items/resourceTraitor.js
- src/data/items/slotChest.js
Traitor Double E-Sword: Power 14 -> 23
Ling Arm Enhancement: 689 sell price -> 15300
Ling Reinforced Body: 834 sell price -> 18750
> Traitor DES power buff, Ling armor sell price buff

- src/data/bartending.js
- src/data/ling.js
Fixes the ability names on the second and third flesh ling crafting abilities.
Fixes anti-freeze only making one item.
> Fixes Ling names and Antifreeze rate

- src/data/enemies/arrivalLounge.js
- src/data/items/shop.js
- src/data/ling.js
Misc: lowers the drop rate of the bluespace tomato from the janitor
Rebalances the first 4 chests. You now have a 50% chance of a unique/semiunique item. This was generally a buff.
Ling: Adds a changeling armblade. This is created on joining the job OR as a drop from the lavaland crate.
> 1 Week Ling Cult Balance

- src/data/items/resourceChemistry.js
- src/state/cargonia.js
Nerf: The social lubricant only has a 50% chance to give you power equal to your money. Engineers have gotten wise to your bribery.
> 1 Week Cargonia Nerfs

- src/data/bartending.js
Reduces the quantity of drinks made for slime drinks to 4 for 1 slime drinks.
> 1 Week Bartending Nerf

- src/data/items/slotJumpsuit.js
Fixes it saying 30, previously 50.
> Jumpsuit Fix

- src/data/enemies/hopLine.js
Removes the extra diamond drop from HOP, replacing it with 1-10 gold.
> Removes the extra diamond drop from HOP

- src/state/validhunting.js
this is some standout bad code in such a clean codebase
> cham jumpsuit gives validhunting boost

- src/data/enemies/boss50-cult.js
Lowers the dodge chance by 5
Increases the power by 5
Lowers the resistance by another 10.
> Nerfs the Wraith

- src/data/items/resourceTraitor.js
This will make them more obviously stand out as distinct from their non-traitor counterparts
> traitor eswords now have custom descriptions

- src/data/items/slotChest.js
> Assault Mechs count as mechs too

- src/data/items/resourceTraitor.js
Exactly what it says on the tin.
> Also makes the traitor mech a mech

- README.md
Hi all -
This is just a small update to the documentation on the section "Setup and Deployment", as it was missing a few key bits that personally caused me grief coming in as a noob. I'll see about the rest of the documentation later on, if there's demand for it.
Thanks!
- Added "Prerequisites" section detailing installing Vue CLI and requirements.
- Added a lot of detail in "Deploy To Github" about editing files for personal use.
- Added detail text to "Project Setup".
- Edited introduction section.
> Documentation Update 1

- src/components/Content/ContentCompletion.vue
- src/state/completion.js
Reverts TBartl/space-station-13-idle#389
> Revert "Hiding items from completion: "Nocomplete" Item Key"

- src/data/items/shop.js
- src/data/items/slotCompanion.js
I LOVE skub so I decided to share it all with you, just to annoy the anti-skub folk.
Anyway, adds a skub companion that's just cosmetic; objectively the best companion you'll ever need throughout the game.
This also replaces The Liberator hat drop from the revolution crate since its something you get from the normal hat crate anyway.
> Adds skub companion

- src/data/items/slotFace.js
- src/data/items/slotHead.js
Face2.0 items are now no complete until R&D is added.
> Face2.0 items are no complete

- src/data/enemies.js
- src/data/upgrades.js
- src/data/zones.js
Enemies and items still exist in the game to not corrupt saves, but you can't access the zones anymore.
> Ends halloween and bugfix

- src/data/ling.js
Buffs the xp rate on changeling
> Buffs the xp rate on changeling

- src/data/items/shop.js
Changes the description of antag job start items to include the black ops communicator for ease of understanding.
> Antag items desc update

- src/components/ItemRequirement.vue
- src/data/items/resourceCult.js
- src/data/items/resourceEngineering.js
- src/data/researchBounties.js
- src/state/jobSingleAction.js
- src/state/research.js
- negative item bugs fixed! (not thoroughly tested but fine in theory?)
equipping an item now makes your total for tasks/item bounties get a -1 penalty,
effectively meaning you can't use up an item you're currently wearing
- rebalanced the engi/cult researchable weapons a bit (cattle prod buffed particularly)
- made a sucky item bounty less sucky
> 1.4 Week 1 fixes and tweaks

- src/components/Content/ContentGraytiding.vue
idk why this was never just made a global rule for all the jobs with sections but im too lazy to change it
> Fix tiding css

- src/data/items/slotHand.js
Having the Armblade give some form of regeneration is fitting for a changeling and a few people were talking about giving ling a refreshment.
> Armblade gives a little regen now

- src/components/Content/ContentInventory.vue
- src/components/Content/ContentSettings.vue
- src/components/Content/Inventory/InventoryItem.vue
- src/state/settings.js
- Shift-click an item in your inventory to instantly sell all of it
- A new setting has been added that will show an option to sell all but one of an item in your inventory when it's enabled
> Selling QoL

- src/data/recipes.js
Tested locally, functional
Fixes #449
> Fixes flash research

- src/data/items/resourceChemistry.js
> Fixes Ballmer Fluid Description

- src/state/store.js
> Fixes bug with selling nan-value items

- src/components/Content/ContentShitposting.vue
honestly player references are bad
> Genericizes Shitposting

- src/data/mining.js
- src/state/mining.js
Includes fixed potion and tool interactions
> Fixes new mining task
