src/data/chemistry.js, src/data/fabrication.js, src/data/items/foodBotany.js, src/data/items/foodCooking.js, src/data/items/resourceGraytiding.js, src/data/items/resourceMining.js, src/data/items/resourceTinkering.js, src/data/items/slotHand.js, src/data/xenobiology.js
The following skills have had economy values added. The income is relatively even between all jobs at 1 per second per level of skill. This is BEFORE any upgrades are accounted for so I'm sure they'll make things interesting (I'm counting on it).
**Mining**
All
**Fabrication**
Just the guns
**Botany**
This was a fun one, since it tried to take into account seeds and the fact that they grow in batches
**Cooking**
Also fun because it was taking into account Botany prices which were all over the place.
**Greytiding**
Despite being unlocked at level 1, junk is treated as a level 25 item. This is because it never improves. Great money maker at the start of the game, worse later.
**Tinkering** 
Flammable junk only, The rest of the skill needs a look over on xp values.
**Xenobiology**
Readds the …
=> The Start Of An Economy

src/data/enemies.js, src/data/engineering.js, src/data/graytiding.js, src/data/items/slotChest.js, src/data/items/slotCompanion.js
Fix Oil Barrel time, Generator 2 level requirement
BUFFS Chest slots HP. 10 to 60 more HP depending on the level (20-55 for mechs)
BUFFS non xenobiology run chances SIGNIFICANTLY
BUFFS seeds from greytiding slightly
Nerfs non slime companion stats.
Buffs coin drops from enemies from 0-3 to 0-5 multiplied by robustness
=> Early combat buffs, minor fixes

src/data/enemies/arrivalLounge.js, src/data/enemies/bridge.js, src/data/enemies/maintenance.js, src/data/enemies/medical.js, src/data/enemies/science.js, src/data/enemies/virology.js, src/data/items/resourceTinkering.js, src/data/items/slotChest.js, src/data/tinkering.js
Changes (lower) sell prices on tinkering chests.
Nerfs? (reduces) the combat stats of the first two enemies
Lowers the requirements to create flammable junk as well as time and XP.
Improves some mid-late game combat drop tables. More work to come in the future still here.
=> Chest sell prices, Flame junk, and Combat Drop Tables

src/data/items/foodBotany.js, src/data/items/foodCooking.js, src/data/items/foodOther.js, src/data/items/slotChest.js, src/data/items/slotCompanion.js, src/data/items/slotFace.js, src/data/items/slotHead.js, src/data/items/slotJumpsuit.js, src/data/items/slotLimb.js, src/data/items/slotNeck.js
Botany food now heals for DOUBLE
Cooked foods are now approximately double
Items that used some of their power budget have been buffed. 1 point = 10 health.
All values below are at max level
BUFFS Chest max health bonus up to 210 (nonmechs)
BUFFS Head max health bonus up to 90
BUFFS Limb max health bonus up to 60
BUFFS Jumpsuit max health bonus up to 50
BUFFS Neck max health bonus up to 20
BUFFS Face max health bonus up to 30
BUFFS Xenobiology health bonuses (max remained the same but more provide it)
=> Upgrades the healing and health components on ALL

src/data/cooking.js
Fix: Copypasta now correctly takes 2 Pasta to create.
New Content: Adds the ability to cook with Quality Pasta to cooking. This is at the very bottom of the skill.
=> Fixes Copy Pasta, Adds Quality Pasta Cooking

src/data/items/slotHand.js
FIX: Energy Guns Now do burn damage
For future notice this is done automatically at the bottom. The rest of automatic gun statting is still disabled.
=> FIX: Energy Guns Now do burn damage

src/data/fabrication.js
Reduces the firefighter craft cost glass: 30, silver: 45, gold: 50, titanium: 5. This does not change the stats or cost of the firefighter mech.
=> Firefighter Fix

src/data/graytiding.js
Chemistry greytiding had two oxygen rewards, and no water reward.
This removes the duplicate and adds water, so all bases are a potential reward.
=> Removes duplicate reward for chemistry greytiding.

src/components/Content/Combat/StatsPanel.vue, src/components/Content/ContentCombatJobInfo.vue, src/components/Content/ContentTinkering.vue, src/data/chemistry.js, src/data/enemies/boss1-security.js, src/data/enemies/boss2-lavaland.js, src/data/enemies/boss3-antag.js, src/data/engineering.js, src/data/items/foodBotany.js, src/data/items/resourceChemistry.js, src/data/upgrades.js, src/state/engineering.js
Fixes cultist of ratvar name
Changes miner sprite
Edits the null rod sprite with a community suggestion. Thanks zRedwind
Buffs energy drink to x4
Increases money drops off bosses significantly (up to 50,000)
Buffs the super glue to 30%, reduces charges to 5
Increases meat drops off bosses x5-25
Changes instances of dodge to evade
Nerfs mining upgrade to 15% from 20%
Reduces botany sell costs increasing as you go up in tier.Removes the 5 hp bonus from botany foods
=> Lots of small changes, Income Upgrades Bosses

src/data/tinkering.js
This changes the Officer's Sabre (meleesharp7)'s crafting time from 43 seconds to 10, to fit in line with every other tinkering recipe.
=> Officer's Sabre Tinkering Time

src/components/Content/ContentChemistry.vue, src/components/Content/ContentMining.vue, src/data/chemistry.js, src/data/fabrication.js, src/data/graytiding.js, src/data/items/resourceMining.js, src/data/mining.js
Switches iron and glass around, mostly
Reasons:
* Harvesting sand is easier than iron as it is everywhere, better thematically
* The miner guide tells you to pound sand
* Shotguns and shotgun ammo now need iron instead of glass, better thematically
* Base powercells require glass, which better represents how you need some of it in ss13 to actually make cells
* Handily, base mechs getting the ore switched works out better because the first mech you unlock is the ripley with glass cage, using the most glass (100) out of all mechs.
I changed potions that needed iron as an element to now need glass for a "special beaker" (only affects fauna perfume and glue) mostly because I feel like keeping the iron requirement would be a bigger balance change than the ones below.
Things unchaged, resulting …
=> Switches iron and glass around in mining, fabrication and chemistry - But not in drops.

src/components/Content/ContentSettings.vue, src/state/mob.js, src/state/settings.js
This PR will add an extra option to the Settings menu to automatically cancel combat should their pockets become empty (run out of ammo). This setting is set to false by default.
This can help AFK farming sessions from disaster when a player runs out of ammo and finds themselves helpless against the enemy they've chosen to farm. It will, however, destroy all loot upon running out of ammunition, but if players decide to turn this on, their equipment is probably more valuable than their loot.
=> Add option to cancel combat when pockets get empty

src/components/ItemRequirement.vue, src/state/inventory.js, src/state/jobSingleAction.js
This PR will allow players to craft items that require items that are currently equipped for combat such as food and ammunition.
Equipped items are shown on the action panel just the same as if they were part of the player's bank.
**NOTE:** To facilitate this change, I made a change to setter `inventory/changeItemCount` such that it no longer checks if we are trying to change the equipped item's count by a negative amount. I think the only reason for this check was to allow zeroing out bank items when an item was equipped, but I am not completely familiar with the codebase yet. Please sanity check me!
I'm also not 100% happy with the code duplication of `changeItemCount` and `moveBankToEquipment`/`moveEquipmentToBank` and how they modify the bank state, but I couldn't find a cleaner way. …
=> Allow crafting with equipped items

src/data/enemies/bridge.js
The captains locker has been reinforced from 20% armor rating to 25% armor rating. This is to account for the stored propaganga.
=> Increases the lockers protection rating

src/state/cooking.js
Fixes #240. 
The cooking potion was set to be used if EITHER the fry cooking upgrade or the potion was available. However, due to the way that the potion only augments fry cooking, it is useless on its own.
This PR will set cooking actions to preserve their potion when fry cooking is unavailable or disabled.
(I also removed a redundant if-statement I noticed in the process.)
=> Fix cooking potion usage

src/state/inventory.js
When changing equipment with a full inventory, while equipped item is marked as not unequipable, equipping a stacked item from bank causes equipped item to dissapear.
https://cdn.discordapp.com/attachments/726850000125952101/731794284000575548/inventorybug.gif
fireaxe dissapears
=> Fixes dissapearing items upon changing equipment.

src/state/cooking.js
A follow-up to #267 after further discussion.
Allows the use of the cooking potion even when fry cooking is disabled or not yet unlocked. This still fixes the issue of #240, as cooking potions are consumed and have their intended effect.
=> Allow potion use with fry cooking disabled

src/components/Content/ContentCompletion.vue, src/state/chrono.js, src/state/completion.js, src/state/store.js
This PR will add a small box to the Completion section indicating how many times the player has reset so far. It is not shown before the first reset.
=> Add tracking for resets

src/data/cult.js, src/data/items/foodBartending.js, src/data/items/slotNeck.js, src/data/traitor.js
Fix:
Fixes the order of rune unlocks.
Adds the clown jumpsuit as the level 1 item to traitor, and removes the level 10 requirement from the jumpsuit.
Nerf
Reduces the sell price of bartending items by approximately 20%. It should still be good money.
Reduces the stats on the cursed touch item.
=> Cult+Traitor Fix, Bartending+Cursed Touch Nerf.

src/data/items/slotLimb.js, src/data/items/slotNeck.js
Fix: The Rune of Attor has the correct overlay sprite
Nerf/Fix: The first two material cult runes no longer have additional luck.
=> Removes luck from 2 cult runes and Fixes Attor Overlay

src/data/cargonia.js, src/data/cult.js, src/data/ling.js
Increases the XP for cult pets sacrifices, as well as changing the times and favor requirements. In general it should be more rewarding to craft them now for XP.
Fixes the xp on the second cargo smuggling action and the action time on the popular disguise.
=> Increases Cult Pet Times and XP. Fix of 2 typos

src/data/items/slotJumpsuit.js, src/data/traitor.js
Traitor Nerfs:
Combat Jumpsuit: The jumpsuit has been reduced from 7 in all stats to 4 in all stats, as well as a 4 command requirement. This is still an amazing early game push, but no longer a solid 20+ stat points above other items.
Chameleon Jumpsuit: XP Bonus's have been reduced from 50% to 30%. This could have remained if the rest of the job wasn't such go juice.
Consumables: All non ammo consumables have been reduced by 90%. They were allowing people to completely skip creating food, which was not the intention.
=> 1 Week Traitor Nerf

src/data/bartending.js
We're all probably tired of hearing about how this drink shouldn't be in that category so I'm just offering to change the drink categories from "Virgin" and "Alcoholic" to "Basic" and "Complex". Maybe now they will stop bugging over it.
Changes:
- "Virgin" is now called "Basic Drinks"
- "Alcoholic" is now called "Complex Drinks"
- "Super Virgin" is now called "Super Basic Drinks"
- "Super Alcoholic" is now called "Super Complex Drinks"
This doesn't change anything pertaining to item codes and from my testing nothing is affected negatively. It seems like the simplest way to fix this without changing everything around and unnecessarily complicating things for the sake of complicating things.
=> Minor Bartending Name Changes

src/components/Content/Shop/ShopPurchase.vue, src/data/items/shop.js
Antag job starter items from crates (for cargonia and ling) are now their own item table independently rolled from the rest of the crate contents
Consequently they are much more likely to drop, with a flat 25% chance to get them from any given crate
Also fixes a bug in the shop menu .vue that broke viewing odds for items with itemTables values
Flash max payout has been reduced, one crate can give up to 5 flashes down from 10
Coderbus also suggested maybe nerfing the flash if this makes them too farmable, I disagree but it's up to the code owners
This PR was inspired by my 20 revolution supply caches with no flashes, and therefore no cargonia :(
=> Changes how antag job starter items are dropped from crates

src/components/Content/Combat/RobustnessBadge.vue, src/components/Content/Combat/StatPanelItem.vue, src/components/Content/Combat/StatsPanel.vue
fixes #353 
Issue: mousing over a b-popover while within another b-popover causes the initial b-popover to disappear as shown in issue #353 
Cause: the hover event for the higher level b-popover switches to false and the b-popover disappears when you mouse over the other b-popover
Fix: I added pointer-events: none to the most nested b-popover so that the hover event still applies to the main b-popover. I applied this fix to equipment page (shown in gif in issue #353 ) as well as robustness badge.
Additional: Also changed delay from 0 to 50 for robustness badge or else the b-popover for robustness disappears when you try to mouse up over it unless you do it in just the right way.
=> Issue 353: fix popover disappearing

src/components/Content/ContentCombatJobInfo.vue
fixes #352 
Issue: Toggling between Stats? and Robustness? buttons on Validhunting tutorial caused an error.
Cause: The cause of this issue is the Robustness? slot in ContentCombatJobInfo.vue, however after some time looking over it I don't actually know why this error is occurring and would love for someone to explain it if anyone figures it out.
Issue 352: Validhunting Tutorial Gamebreaking Runtime
Fix: There were a couple things that could stop the bug from occurring:
- changing the template tag for Robustness? slot to another tag like div fixes it
- commenting out the two img tags line 163, 164 fixes it
- wrapping the content of the Robustness? slot with a div fixes it.
I went with the 3rd options because it seemed the cleanest/least obtrusive.
I legitimately have no idea why this bug …
=> Issue 352: Validhunting Tutorial Gamebreaking Runtime

src/data/items/shop.js
- ERT crate (Nanotrasen droppod) now drops the Traitor variant of the energy sword instead of the regular energy sword (reduces completionist grind a bit)
- ERT crate no longer drops lethal cells
- ERT crate will now drop 1000-1500 disintegration cells, up from 1-100
- ERT crate weights rebalanced a bit so the odds of getting one of the unique drops is roughly 45%
- ERT crate will now drop 3-5 casualty propaganda, up from 1-3
- Wizard crate imprinted telecrystals are twice as likely to drop
=> Lategame crates rebalancing

src/state/mob.js
This is a single line change, which enables you to specify `preserve: true` in any pocket item. It will not be consumed on attack if this is true. If missing or false, it behaves as normal.
=> Enables "Preserve" option.

src/components/Content/ContentCompletion.vue, src/state/completion.js
Thanks to PKPenguin321 for help with this.
This adds the ability to add unobtainable items to the live game without affecting completion.
In an item's keys, where you'd put things such as `name` and `sellPrice`, you can add `nocomplete`, and give it a boolean value of `true` to hide the item from the Completion GUI, and force it to give no % to completion if obtained via cheat menu.
If you don't make the item obtainable through some means, it will be completely invisible to non-cheating players.
=> Hiding items from completion: "Nocomplete" Item Key

src/components/Content/ContentCompletion.vue, src/state/completion.js
It works properly now, had to add an entire process of logic to make it function. Interesting how the previous solution was so obvious and said it would do what we wanted it to do, but it didn't do *all* of it.
- `ContentCompletion.vue`: Added logic to filter the ITEMS object, and used it. Removed the previous "`return ITEMS;`.
- `completion.js`: Changed the `itemPercent` logic to count 100% as "All items besides those marked 'nocomplete'. Note that the items will still give % towards 100%, but you can and will go over if you gave yourself every item in the code.
Let's hope it doesn't break when you push it to live this time. It works fine for me.
- Change line 180's `itemId.nocomplete` to `!itemId.nocomplete` to only show items marked `nocomplete` in the completion list. Useful for …
=> Nocomplete v2

src/data/upgrades.js
~~Don't merge this yet, haven't tested it. Just a quick and dirty one liner with the web editor atm.~~
Did this because I showed a friend the game and they were really confused what Black Ops Efficiency upgrades would do (they had 0 antag jobs).
=> Black Ops Efficiency upgrade locked behind having at least 1 antag job

src/data/items/resourceValidhunting.js
After the original descriptions, they newline and say "5 of these will allow you to fight a boss in/at/on/from the [X]".
=> Propaganda items have functionality tips in their descriptions

src/data/recipes.js
This error makes the Ling tool research not disappear once purchased, oops
=> Fixes a copypaste error

src/assets/GlobalStyle.css, src/components/Content/ContentBartending.vue, src/components/Content/ContentBotany.vue, src/components/Content/ContentCargonia.vue, src/components/Content/ContentChemistry.vue, src/components/Content/ContentCooking.vue, src/components/Content/ContentCult.vue, src/components/Content/ContentEngineering.vue, src/components/Content/ContentFabrication.vue, src/components/Content/ContentGraytiding.vue, src/components/Content/ContentLing.vue, src/components/Content/ContentMining.vue, src/components/Content/ContentResearch.vue, src/components/Content/ContentSettings.vue, src/components/Content/ContentShitposting.vue, src/components/Content/ContentTinkering.vue, src/components/Content/ContentTraitor.vue, src/components/Content/ContentXenobiology.vue, src/components/Content/ExperienceHeader.vue, src/components/Sidebar/Sidebar.vue, src/state/settings.js
"Top bar" meaning the XP bar and potion slot on each job
- The top bar of each job will now stick to the top of the screen as you scroll down
- There is now a setting that will replace the XP counter in the top bar with the XP required to level up
- There is now a setting to hide locked jobs from the sidebar
Previews:
https://user-images.githubusercontent.com/8345184/169980265-be54fcd1-c4b6-4878-8d00-c7be338d33b0.mp4
https://user-images.githubusercontent.com/8345184/169985654-b6a86c19-3ce3-464c-8509-77df5bd236fb.mp4
=> Top/Side Bar Improvements

src/state/validhunting.js
This fix prevents your rerolls from exceeding your max. Oops
=> Validhunting max rerolls hotfix

src/data/engineering.js
Seems like the advanced one and basic one had ex levels flipped
The jump of XP from Portable Generator seems like a mistake.
=> Fixes XP for generators
